-- ── ATTENDANCE ───────────────────────────────────────────────────────────────
-- This relation already exists in the production Supabase project (created
-- outside repo migrations, like most non-academic tables). Captured here so a
-- deployment provisioned from this repository gets the same relation the app
-- queries (admin overview "Attendance today" KPI). Idempotent on the live DB.

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  student_name text not null,
  homeroom text,
  attendance_date date not null,
  present boolean not null default true,
  tardy boolean not null default false,
  excused boolean not null default false,
  notes text,
  submitted_by text,
  school_year text not null default '2025-26',
  school_id text not null default 'wayne-stem',
  created_at timestamptz default now()
);

create index if not exists att_date on attendance(attendance_date desc);
create index if not exists att_student_date on attendance(student_name, attendance_date desc);

alter table attendance enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public'
    and tablename = 'attendance' and policyname = 'authenticated users can read attendance') then
    create policy "authenticated users can read attendance"
      on attendance for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public'
    and tablename = 'attendance' and policyname = 'authenticated users can insert attendance') then
    create policy "authenticated users can insert attendance"
      on attendance for insert to authenticated with check ((select auth.uid()) is not null);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public'
    and tablename = 'attendance' and policyname = 'authenticated users can update attendance') then
    create policy "authenticated users can update attendance"
      on attendance for update to authenticated using ((select auth.uid()) is not null);
  end if;
end
$$;
